language: cpp

script: 
  - mkdir Build
  - cd Build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER ..
  - make
  - make test

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: 
        - COMPILER=g++-4.9

addons:
  apt:
    packages:
      - libpcap-dev
