language: cpp

script: 
  - mkdir Build
  - cd Build
  - cmake ..
  - make
  - make test


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - CXX=g++-4.9
        - CC=gcc-4.9
